// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UeesDigital.Infrastructure.Persistence;

#nullable disable

namespace UeesDigital.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("UeesDigital.Domain.Entities.Carrera", b =>
                {
                    b.Property<int>("IdCarrera")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCarrera"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IdFacultad")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCarrera");

                    b.HasIndex("IdFacultad");

                    b.ToTable("Carreras");

                    b.HasData(
                        new
                        {
                            IdCarrera = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id = new Guid("aaaaaaaa-0001-0000-0000-000000000000"),
                            IdFacultad = 1,
                            IsDelete = false,
                            Nombre = "Ingeniería en Desarrollo de Software y Ciencia de Datos"
                        },
                        new
                        {
                            IdCarrera = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id = new Guid("aaaaaaaa-0002-0000-0000-000000000000"),
                            IdFacultad = 1,
                            IsDelete = false,
                            Nombre = "Ingeniería en Tecnologías Emergentes y Robótica"
                        },
                        new
                        {
                            IdCarrera = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id = new Guid("aaaaaaaa-0003-0000-0000-000000000000"),
                            IdFacultad = 1,
                            IsDelete = false,
                            Nombre = "Técnico en Ciberseguridad"
                        },
                        new
                        {
                            IdCarrera = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id = new Guid("aaaaaaaa-0004-0000-0000-000000000000"),
                            IdFacultad = 2,
                            IsDelete = false,
                            Nombre = "Licenciatura en Administración de Empresas"
                        },
                        new
                        {
                            IdCarrera = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id = new Guid("aaaaaaaa-0005-0000-0000-000000000000"),
                            IdFacultad = 2,
                            IsDelete = false,
                            Nombre = "Licenciatura en Marketing"
                        },
                        new
                        {
                            IdCarrera = 6,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id = new Guid("aaaaaaaa-0006-0000-0000-000000000000"),
                            IdFacultad = 2,
                            IsDelete = false,
                            Nombre = "Técnico en Marketing Digital"
                        },
                        new
                        {
                            IdCarrera = 7,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id = new Guid("aaaaaaaa-0007-0000-0000-000000000000"),
                            IdFacultad = 2,
                            IsDelete = false,
                            Nombre = "Licenciatura en Relaciones Públicas con especialidad en Marketing"
                        },
                        new
                        {
                            IdCarrera = 8,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id = new Guid("aaaaaaaa-0008-0000-0000-000000000000"),
                            IdFacultad = 3,
                            IsDelete = false,
                            Nombre = "Licenciatura en Ciencias Jurídicas"
                        },
                        new
                        {
                            IdCarrera = 9,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id = new Guid("aaaaaaaa-0009-0000-0000-000000000000"),
                            IdFacultad = 3,
                            IsDelete = false,
                            Nombre = "Licenciatura en Relaciones y Negocios Internacionales"
                        },
                        new
                        {
                            IdCarrera = 10,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id = new Guid("aaaaaaaa-0010-0000-0000-000000000000"),
                            IdFacultad = 4,
                            IsDelete = false,
                            Nombre = "Licenciatura en Psicología"
                        },
                        new
                        {
                            IdCarrera = 11,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id = new Guid("aaaaaaaa-0011-0000-0000-000000000000"),
                            IdFacultad = 4,
                            IsDelete = false,
                            Nombre = "Licenciatura en Lenguas Modernas en Inglés y Francés"
                        },
                        new
                        {
                            IdCarrera = 12,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id = new Guid("aaaaaaaa-0012-0000-0000-000000000000"),
                            IdFacultad = 4,
                            IsDelete = false,
                            Nombre = "Licenciatura en Teología"
                        },
                        new
                        {
                            IdCarrera = 13,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id = new Guid("aaaaaaaa-0013-0000-0000-000000000000"),
                            IdFacultad = 4,
                            IsDelete = false,
                            Nombre = "Licenciatura en Traducción e Interpretación del Idioma Inglés"
                        },
                        new
                        {
                            IdCarrera = 14,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id = new Guid("aaaaaaaa-0014-0000-0000-000000000000"),
                            IdFacultad = 4,
                            IsDelete = false,
                            Nombre = "Profesorado y Licenciatura en Educación Inicial y Parvularia"
                        },
                        new
                        {
                            IdCarrera = 15,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id = new Guid("aaaaaaaa-0015-0000-0000-000000000000"),
                            IdFacultad = 5,
                            IsDelete = false,
                            Nombre = "Doctorado en Medicina"
                        },
                        new
                        {
                            IdCarrera = 16,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id = new Guid("aaaaaaaa-0016-0000-0000-000000000000"),
                            IdFacultad = 5,
                            IsDelete = false,
                            Nombre = "Licenciatura en Enfermería"
                        },
                        new
                        {
                            IdCarrera = 17,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id = new Guid("aaaaaaaa-0017-0000-0000-000000000000"),
                            IdFacultad = 5,
                            IsDelete = false,
                            Nombre = "Licenciatura en Nutrición y Dietética"
                        },
                        new
                        {
                            IdCarrera = 18,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id = new Guid("aaaaaaaa-0018-0000-0000-000000000000"),
                            IdFacultad = 5,
                            IsDelete = false,
                            Nombre = "Técnico en Enfermería"
                        },
                        new
                        {
                            IdCarrera = 19,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id = new Guid("aaaaaaaa-0019-0000-0000-000000000000"),
                            IdFacultad = 5,
                            IsDelete = false,
                            Nombre = "Doctorado en Cirugía Dental"
                        },
                        new
                        {
                            IdCarrera = 20,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id = new Guid("aaaaaaaa-0020-0000-0000-000000000000"),
                            IdFacultad = 5,
                            IsDelete = false,
                            Nombre = "Técnico en Asistencia Odontológica"
                        });
                });

            modelBuilder.Entity("UeesDigital.Domain.Entities.Estudiante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<int>("Carnet")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdCarrera")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdCarrera");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("UeesDigital.Domain.Entities.Facultad", b =>
                {
                    b.Property<int>("IdFacultad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFacultad"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdFacultad");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Facultades");

                    b.HasData(
                        new
                        {
                            IdFacultad = 1,
                            Codigo = "FI",
                            Nombre = "Facultad de Ingeniería"
                        },
                        new
                        {
                            IdFacultad = 2,
                            Codigo = "FCE",
                            Nombre = "Facultad de Ciencias Económicas"
                        },
                        new
                        {
                            IdFacultad = 3,
                            Codigo = "FCJ",
                            Nombre = "Facultad de Ciencias Jurídicas"
                        },
                        new
                        {
                            IdFacultad = 4,
                            Codigo = "FCS",
                            Nombre = "Facultad de Ciencias Sociales"
                        },
                        new
                        {
                            IdFacultad = 5,
                            Codigo = "FCSA",
                            Nombre = "Facultad de Ciencias de la Salud"
                        });
                });

            modelBuilder.Entity("UeesDigital.Domain.Entities.FechaDisponible", b =>
                {
                    b.Property<int>("IdFechaDisponible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFechaDisponible"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.HasKey("IdFechaDisponible");

                    b.ToTable("FechasDisponibles");
                });

            modelBuilder.Entity("UeesDigital.Domain.Entities.HorarioDisponible", b =>
                {
                    b.Property<int>("IdHorario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHorario"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CuposMaximos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5);

                    b.Property<int>("CuposOcupados")
                        .HasColumnType("int");

                    b.Property<DateTime>("HoraInicio")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IdFechaDisponible")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.HasKey("IdHorario");

                    b.HasIndex("IdFechaDisponible");

                    b.ToTable("HorariosDisponibles");
                });

            modelBuilder.Entity("UeesDigital.Domain.Entities.Tramite", b =>
                {
                    b.Property<Guid>("IdTramite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("CodigoConfirmacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdEstudiante")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IdHorario")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("TipoTramite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTramite");

                    b.HasIndex("CodigoConfirmacion")
                        .IsUnique();

                    b.HasIndex("IdEstudiante");

                    b.HasIndex("IdHorario");

                    b.ToTable("Tramites");
                });

            modelBuilder.Entity("UeesDigital.Infrastructure.Identity.AppIdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("UeesDigital.Infrastructure.Identity.AppIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("UeesDigital.Infrastructure.Identity.AppIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UeesDigital.Infrastructure.Identity.AppIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("UeesDigital.Infrastructure.Identity.AppIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UeesDigital.Domain.Entities.Carrera", b =>
                {
                    b.HasOne("UeesDigital.Domain.Entities.Facultad", "Facultad")
                        .WithMany("Carreras")
                        .HasForeignKey("IdFacultad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facultad");
                });

            modelBuilder.Entity("UeesDigital.Domain.Entities.Estudiante", b =>
                {
                    b.HasOne("UeesDigital.Domain.Entities.Carrera", "Carrera")
                        .WithMany("Estudiantes")
                        .HasForeignKey("IdCarrera")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrera");
                });

            modelBuilder.Entity("UeesDigital.Domain.Entities.HorarioDisponible", b =>
                {
                    b.HasOne("UeesDigital.Domain.Entities.FechaDisponible", "FechaDisponible")
                        .WithMany("Horarios")
                        .HasForeignKey("IdFechaDisponible")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FechaDisponible");
                });

            modelBuilder.Entity("UeesDigital.Domain.Entities.Tramite", b =>
                {
                    b.HasOne("UeesDigital.Domain.Entities.Estudiante", "Estudiante")
                        .WithMany("Tramites")
                        .HasForeignKey("IdEstudiante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UeesDigital.Domain.Entities.HorarioDisponible", "Horario")
                        .WithMany("Tramites")
                        .HasForeignKey("IdHorario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("Horario");
                });

            modelBuilder.Entity("UeesDigital.Domain.Entities.Carrera", b =>
                {
                    b.Navigation("Estudiantes");
                });

            modelBuilder.Entity("UeesDigital.Domain.Entities.Estudiante", b =>
                {
                    b.Navigation("Tramites");
                });

            modelBuilder.Entity("UeesDigital.Domain.Entities.Facultad", b =>
                {
                    b.Navigation("Carreras");
                });

            modelBuilder.Entity("UeesDigital.Domain.Entities.FechaDisponible", b =>
                {
                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("UeesDigital.Domain.Entities.HorarioDisponible", b =>
                {
                    b.Navigation("Tramites");
                });
#pragma warning restore 612, 618
        }
    }
}
